class_name GodDaggerConstants extends RefCounted


# GodDagger-related constants
const BASE_GODDAGGER_COMPONENT_NAME := "GodDaggerComponent"
const BASE_GODDAGGER_SUBCOMPONENT_NAME := "GodDaggerSubcomponent"
const BASE_GODDAGGER_MODULE_NAME := "GodDaggerModule"
const BASE_GODDAGGER_SCOPE_NAME := "GodDaggerScope"

const GODDAGGER_GRAPH_VERTEX_SCOPE_TAG := "scope"
const GODDAGGER_GRAPH_VERTEX_SCOPE_FILE_PATH_TAG := "scope_file_path"
const GODDAGGER_GRAPH_VERTEX_DEFINITION_TAG := "definition"
const GODDAGGER_GRAPH_VERTEX_FILE_PATH_TAG := "file_path"
const GODDAGGER_GRAPH_VERTEX_PROVISION_METHOD_NAME := "provision_method_name"

const DECLARED_INJECTED_PROPERTY_PREFIX := "__injected_"
const DECLARED_PROVIDER_METHOD_PREFIX := "__provide_"
const DECLARED_SCOPE_METHOD_NAME := "__scope"

const GENERATED_GODDAGGER_TOKEN_PREFIX := "_GodDagger__"

const RENAMED_GODDAGGER_TOKEN_PREFIX := "__goddagger_"
const RENAMED_CONSTRUCTOR_NAME := RENAMED_GODDAGGER_TOKEN_PREFIX + "constructor"

const EXPECTED_INTERFACE_FILE_FORMAT := ".interface.gd"

const GODDAGGER_GENERATED_COMPONENTS_FILE_NAME := "generated_components"

const GODDAGGER_GRAPH_SERIALIZED_KEY_NAME := "name"
const GODDAGGER_GRAPH_SERIALIZED_KEY_VERTICES := "vertices"
const GODDAGGER_GRAPH_SERIALIZED_KEY_VERTEX_NAME := "vertex_name"
const GODDAGGER_GRAPH_SERIALIZED_KEY_TAGS := "tags"
const GODDAGGER_GRAPH_SERIALIZED_KEY_TAG_NAME := "tag_name"
const GODDAGGER_GRAPH_SERIALIZED_KEY_TAG_VALUE := "tag_value"
const GODDAGGER_GRAPH_SERIALIZED_KEY_OUTGOING_VERTICES = "outgoing_vertices"

const GODDAGGER_INSPECTOR_PROPERTY_PREFIX := "__goddagger_"
const GODDAGGER_INSPECTOR_TITLE_PROPERTIES := "Properties"
const GODDAGGER_INSPECTOR_TITLE_GRAPH := "Graph"
const GODDAGGER_INSPECTOR_TITLE_INHERITED_GRAPH := "Inherited Graph"

const GODDAGGER_INSPECTOR_PROPERTY_SCOPE_SUFFIX := "Scope"
const GODDAGGER_INSPECTOR_PROPERTY_MODULES_SUFFIX := "Modules"
const GODDAGGER_INSPECTOR_PROPERTY_EXPOSED_DEPENDENCIES_SUFFIX := "ExposedDependencies"
const GODDAGGER_INSPECTOR_PROPERTY_DEPENDENCIES_SUFFIX := "Dependencies"
const GODDAGGER_INSPECTOR_PROPERTY_SUMMARY_SUFFIX := "Summary"

const GODDAGGER_INSPECTOR_PROPERTY_SUBCOMPONENT_LINKING_MODULES_SUFFIX := "Linking Modules"

const GODDAGGER_INSPECTOR_PROPERTY_SUBCOMPONENT_LINKS_SUFFIX := "SubcomponentLinks"
const GODDAGGER_INSPECTOR_PROPERTY_PROVISIONS_SUFFIX := "Provisions"

# Godot Engine or GDScript-related constants
const KEYWORD_CLASS_NAME := "class_name"
const KEYWORD_EXTENDS := "extends"

const CONSTRUCTOR_NAME := "_init"

const KEY_PROPERTY_NAME := "name"
const KEY_PROPERTY_CLASS_NAME := "class_name"

const KEY_METHOD_NAME := "name"
const KEY_METHOD_ARGUMENTS := "args"
const KEY_METHOD_RETURN := "return"

const KEY_ARGUMENT_NAME := "name"
const KEY_ARGUMENT_CLASS_NAME := "class_name"
